- include: ../../commons/tasks/jdk8.yaml
- include: ../../commons/tasks/supervisord.yaml

- name: create user
  user: name=rocketmq state=present
  ignore_errors: yes

- name: Create Base Working Directory
  file: path={{ base }} state=directory mode=0755 owner=rocketmq group=rocketmq

- name: Create App Base Directory
  file: path={{ app_base }} state=directory mode=0755 owner=rocketmq group=rocketmq
 
- name: Create App Data Directory
  file: path={{ data_base }} state=directory mode=0755 owner=rocketmq group=rocketmq
 
- name: Create App Log Directory
  file: path={{ log_base }} state=directory mode=0755 owner=rocketmq group=rocketmq