- name: copy rocketmq to remote servers
  copy: src=rocketmq-console-ng-1.0.0.jar dest={{ appdir }}/

- name: depressing rocketmq console
  file: dest={{ appdir }}/ mode=755 owner=rocketmq group=rocketmq

- name: create direct
  file: path={{ logdir }}-console state=directory mode=0755 owner=rocketmq group=rocketmq

- name: Update mqconsole
  template:
    src: rocketmq-console-ng.ini.j2
    dest: "/etc/supervisord.d/rocketmq-console-ng.ini"
    force: true
    owner: root
    group: root
    mode: "0755"
  notify: update supervisord
